### ISSUE TITLE
No longer works with Angular CLI

### ISSUE THREAD

**Issue by woosanghun** [US-CBP/ngx-cbp-theme#24]
I'm getting a ton of "Cannot find module '@angular/core'" messages.   Is it possible that this is caused by the library being built on a release candidate version?   Tried cloning **my-app** and got similar errors.

**Comment by yogeshgadge** [comment]
Most likely. 
Let me take a look at my-app. 

Also the readme.md getting started has few issues that needs fixes brought to my attention. 

We want to lock the versions after Material 2 gets to next release. 

They are introducing a breaking change and we had to use 4.40.RC to get some of those features.

**Comment by yogeshgadge** [comment]
Use angular-cli 1.3.2
