### ISSUE TITLE
Handle SSO or User Already logged in

### ISSUE THREAD

**Issue by yogeshgadge** [US-CBP/ngx-cbp-theme#44]
Currently we expect user to click on Login on the Header however as a step towards getting SSO ready we need some provisions.

**Comment by walhow** [comment]
We need to be able to support an already logged in scenario. Our application sits behinde WebSEAL, which handles the login page. We are using Angular's APP_INITIALIZER to run a check before application is bootstrapped, so I'd like to be able to display the users name right off the bat, not the Login message.

**Comment by yogeshgadge** [comment]
Fixed by PR#44 version 2.1.3

Try something like this in your `app.module.ts`

https://github.com/US-CBP/ngx-cbp-theme/blob/c533d6ed36d980513056f9563a039db9d83f0504/src/demo/app/demo.module.ts#L54-L57
